name: Node.js build as Export

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'  

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build 

      - name: verify output folder
        run: ls -l out